### ISSUE TITLE
How to construct the 'hier' or 'edges'?

### ISSUE THREAD

**Issue by wandli** [soumyac1999/hyperbolic-label-emb-for-hmc#5]
Hello,

I found that the class 'TextLabelDataset' have a parameter 'hier_file', which is responsible for generating 'edges' for trainvalset and other datasets. 

However, I didn't find any code that creates the 'hier_file' (I'm using yelp). Would you please provide some hints?

Thanks in advance.

**Comment by ayushbits** [comment]
You can find the taxonomies for each dataset inside data_utils/ folder.

**Comment by wandli** [comment]
but I think the 'edges' is not returned in the __getitem__ method of datasets.py .
