### ISSUE TITLE
No file called rcv1/docs.txt

### ISSUE THREAD

**Issue by splendidbug** [soumyac1999/hyperbolic-label-emb-for-hmc#6]
Hi, I am able to find all the files in `data_utils/readData_rcv1.py` except for `rcv1/docs.txt`. Could you please help me out?

**Comment by soumya-ch** [comment]
Hi, request you to refer to issue #4. Specifically [this comment](https://github.com/soumyac1999/hyperbolic-label-emb-for-hmc/issues/4#issuecomment-957294380).
In short, RCV1 is a proprietary dataset and the instructions for getting access to it can be found [here](https://trec.nist.gov/data/reuters/reuters.html).
